[project]
name = "neural-style-transfer"
version = "0.1.0"
description = "Neural Style Transfer"
requires-python = ">=3.8,<=3.12"
readme = "README.md"
dependencies = [
    "jupyter",
    "matplotlib",
    "tdqm",
    "torch",
    "torchvision",
]
